version: "3.3"

services:
  app:
    build: .
    command: make train
    volumes:
      - ./submission:/app
#      - ./tests/train_data_sample:/app/data
      - ../idao_2021_train:/app/data
      - ./generated_submissions:/submissions
    working_dir: /app
